[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fontbench"
version = "0.1.0"
description = "Collection of tools and experiments to diagnose and quantitatively analyze Chinese typefaces."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "glyphsLib",
    "numpy",
]

[project.optional-dependencies]
dev = [
    "pandas",
    "tqdm",
    "pyvips",
    "cairosvg",
    "Pillow",
]

[tool.setuptools]
packages = ["fontbench"]

